version: '2.1'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile-nb
    extends:
      file: docker-compose.yml
      service: python
    volumes:
      - .:/src
    environment:
      BASE_DJANGO_APP_NAME: mitxpro
    command: >
      /bin/bash -c '
      sleep 3 &&
      jupyter notebook --no-browser --ip=0.0.0.0 --port=8080'
    ports:
      - "8080:8080"
