version: '3.6'
services:
  web:
    build:
      context: .
      # TODO: upload dockerfile first then uncomment this line
      # dockerfile: ./travis/Dockerfile-travis-web
      dockerfile: ./Dockerfile
      target: webapp

  celery:
    build:
      context: .
      # TODO: upload dockerfile first then uncomment this line
      # dockerfile: ./travis/Dockerfile-travis-web
      dockerfile: ./Dockerfile
      target: webapp
    environment:
      # for celery, to avoid ImproperlyConfigured
      MAILGUN_URL: 'http://fake.example.com'
      MAILGUN_KEY: 'fake'
